name: instructify
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  introduction_screen: ^3.0.2
  flutter_native_splash: ^2.1.6
  flutter_svg: ^1.0.3
  auto_size_text: ^3.0.0
  font_awesome_flutter: ^10.1.0
  sizer: ^2.0.15
  flutter_screenutil: ^5.5.3+2
  step_progress_indicator: ^1.0.2
  percent_indicator: ^4.2.2
  material_floating_search_bar: ^0.3.7
  cloud_firestore: ^3.2.1
  firebase_core: ^1.19.1
  dartz: ^0.10.1
  freezed: ^2.0.4
  freezed_annotation: ^2.0.3
  form_validator: ^1.0.2
  firebase_auth: ^3.4.1
  google_sign_in: ^5.4.0
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
  get_it: ^7.2.0
  injectable: ^1.5.3
  shimmer: ^2.0.0
  shared_preferences: ^2.0.15
  flutter_typeahead: ^4.1.0
  change_app_package_name: ^1.1.0
  internet_connection_checker: ^0.0.1+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.10.0"
  injectable_generator:
  flutter_lints: ^2.0.1
  build_runner: ^2.1.11

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/launch_icon.png"
  min_sdk_android: 21 

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash/splash.png

  android: true
  ios: true
  web: true

  android_gravity: fill
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svg/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
