// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcXtVkJvyc0qxWlz7HddwbrFWtUIzy4cY',
    appId: '1:717386503330:web:bb328218d4626c23e4f3fb',
    messagingSenderId: '717386503330',
    projectId: 'instructify-34702',
    authDomain: 'instructify-34702.firebaseapp.com',
    storageBucket: 'instructify-34702.appspot.com',
    measurementId: 'G-7KXDM77HQT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXik9QxshqhTghurR6f13uc_x0lhN1rsw',
    appId: '1:717386503330:android:5784b940bc8468dee4f3fb',
    messagingSenderId: '717386503330',
    projectId: 'instructify-34702',
    storageBucket: 'instructify-34702.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB04qykN7aQUJ4GEP8Gbyv-LnrHMTQEzcU',
    appId: '1:717386503330:ios:e179718f55841fc9e4f3fb',
    messagingSenderId: '717386503330',
    projectId: 'instructify-34702',
    storageBucket: 'instructify-34702.appspot.com',
    iosClientId: '717386503330-pgo78k7l0q7r1grvgq3rgefhd8vfoobr.apps.googleusercontent.com',
    iosBundleId: 'com.example.instructify',
  );
}
